/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.GUI;

import static Client.GUI.Main.menu;
import java.awt.Color;
import java.awt.Image;
import javax.swing.JFrame;

/**
 *
 * @author thoma
 */
public class JPanelGame4 extends javax.swing.JPanel {

    /**
     * Creates new form JPanelGame4
     */
    public JPanelGame4() {
        initComponents();
        this.JPanelUscita.setVisible(false);
        this.JPanelPunteggi.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JButtonEsci = new javax.swing.JButton();
        JPanelUscita = new javax.swing.JPanel();
        JLabelAvvertimento = new javax.swing.JLabel();
        JButtonAbbandona = new javax.swing.JButton();
        JButtonContinua = new javax.swing.JButton();
        JPanelPunteggi = new javax.swing.JPanel();
        LabelG1 = new javax.swing.JLabel();
        LabelG2 = new javax.swing.JLabel();
        LabelP1 = new javax.swing.JLabel();
        LabelP2 = new javax.swing.JLabel();
        JLabelPunteggi = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 0));

        JButtonEsci.setText("Esci");
        JButtonEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEsciActionPerformed(evt);
            }
        });

        JPanelUscita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        JLabelAvvertimento.setText("Sei Sicuro di voler uscire? Perderai la partita automaticamente");

        JButtonAbbandona.setText("Abbandona");
        JButtonAbbandona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAbbandonaActionPerformed(evt);
            }
        });

        JButtonContinua.setText("Continua");
        JButtonContinua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonContinuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelUscitaLayout = new javax.swing.GroupLayout(JPanelUscita);
        JPanelUscita.setLayout(JPanelUscitaLayout);
        JPanelUscitaLayout.setHorizontalGroup(
            JPanelUscitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelUscitaLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(JLabelAvvertimento)
                .addGap(21, 21, 21))
            .addGroup(JPanelUscitaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(JButtonAbbandona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JButtonContinua)
                .addGap(79, 79, 79))
        );
        JPanelUscitaLayout.setVerticalGroup(
            JPanelUscitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelUscitaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JLabelAvvertimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(JPanelUscitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonAbbandona)
                    .addComponent(JButtonContinua))
                .addGap(48, 48, 48))
        );

        LabelG1.setText("Giocatore 1");

        LabelG2.setText("Giocatore 2");

        LabelP1.setText("punteggio1");

        LabelP2.setText("punteggio2");

        JLabelPunteggi.setText("Punteggi");

        javax.swing.GroupLayout JPanelPunteggiLayout = new javax.swing.GroupLayout(JPanelPunteggi);
        JPanelPunteggi.setLayout(JPanelPunteggiLayout);
        JPanelPunteggiLayout.setHorizontalGroup(
            JPanelPunteggiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPunteggiLayout.createSequentialGroup()
                .addGroup(JPanelPunteggiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelPunteggiLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(JPanelPunteggiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelG1)
                            .addComponent(LabelG2))
                        .addGap(56, 56, 56)
                        .addGroup(JPanelPunteggiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelP2)
                            .addComponent(LabelP1)))
                    .addGroup(JPanelPunteggiLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(JLabelPunteggi)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        JPanelPunteggiLayout.setVerticalGroup(
            JPanelPunteggiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPunteggiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(JLabelPunteggi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelPunteggiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelG1)
                    .addComponent(LabelP1))
                .addGap(29, 29, 29)
                .addGroup(JPanelPunteggiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelG2)
                    .addComponent(LabelP2))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/Immagini/yugiohOrrizzontale.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(JPanelPunteggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JPanelUscita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(536, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JButtonEsci)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(203, 203, 203))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(JButtonEsci)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(JPanelPunteggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(JPanelUscita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEsciActionPerformed
        // TODO add your handling code here:
        JPanelUscita.setVisible(true);

    }//GEN-LAST:event_JButtonEsciActionPerformed

    private void JButtonAbbandonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAbbandonaActionPerformed
        // TODO add your handling code here:
        this.JPanelUscita.setVisible(false);
        Main.menu.getContentPane().remove(this);
        Main.menu.add(Main.login);
        Main.menu.pack();
        Main.login.validate();
        Main.login.repaint();
        Main.menu.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_JButtonAbbandonaActionPerformed

    private void JButtonContinuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonContinuaActionPerformed
        // TODO add your handling code here:
        JPanelUscita.setVisible(false);
    }//GEN-LAST:event_JButtonContinuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAbbandona;
    private javax.swing.JButton JButtonContinua;
    private javax.swing.JButton JButtonEsci;
    private javax.swing.JLabel JLabelAvvertimento;
    private javax.swing.JLabel JLabelPunteggi;
    private javax.swing.JPanel JPanelPunteggi;
    private javax.swing.JPanel JPanelUscita;
    private javax.swing.JLabel LabelG1;
    private javax.swing.JLabel LabelG2;
    private javax.swing.JLabel LabelP1;
    private javax.swing.JLabel LabelP2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
