/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.GUI;

import static Client.GUI.Main.menu;
import java.awt.Color;
import java.awt.Image;
import javax.swing.JFrame;

/**
 *
 * @author t.erra
 */
public class JPanelGame extends javax.swing.JPanel {

    /**
     * Creates new form JPanelGame
     */
    public JPanelGame() {
        initComponents();
        this.JPanelUscita.setVisible(false);
        this.JPanelPunteggi.setVisible(false);
        this.JLabelG11b.setVisible(false);
        this.setBackground(Color.BLACK);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelMazzo = new javax.swing.JLabel();
        JLabelG12 = new javax.swing.JLabel();
        JLabelG13 = new javax.swing.JLabel();
        JLabelG11 = new javax.swing.JLabel();
        JButtonEsci = new javax.swing.JButton();
        JPanelUscita = new javax.swing.JPanel();
        JLabelAvvertimento = new javax.swing.JLabel();
        JButtonAbbandona = new javax.swing.JButton();
        JButtonContinua = new javax.swing.JButton();
        JPanelPunteggi = new javax.swing.JPanel();
        LabelG1 = new javax.swing.JLabel();
        LabelG2 = new javax.swing.JLabel();
        LabelP1 = new javax.swing.JLabel();
        LabelP2 = new javax.swing.JLabel();
        JLabelPunteggi = new javax.swing.JLabel();
        JLabelG22 = new javax.swing.JLabel();
        JLabelG23 = new javax.swing.JLabel();
        JLabelG21 = new javax.swing.JLabel();
        JLabelG11b = new javax.swing.JLabel();

        JLabelMazzo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/Immagini/yugiohOrrizzontale.png"))); // NOI18N

        JLabelG12.setBackground(new java.awt.Color(51, 255, 51));
        JLabelG12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/Immagini/yugiohVerticale.png"))); // NOI18N
        JLabelG12.setMaximumSize(new java.awt.Dimension(203, 200));
        JLabelG12.setMinimumSize(new java.awt.Dimension(203, 200));
        JLabelG12.setPreferredSize(new java.awt.Dimension(203, 200));

        JLabelG13.setBackground(new java.awt.Color(51, 255, 51));
        JLabelG13.setForeground(new java.awt.Color(0, 153, 153));
        JLabelG13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/Immagini/yugiohVerticale.png"))); // NOI18N
        JLabelG13.setMaximumSize(new java.awt.Dimension(203, 200));
        JLabelG13.setMinimumSize(new java.awt.Dimension(203, 200));
        JLabelG13.setPreferredSize(new java.awt.Dimension(203, 200));

        JLabelG11.setBackground(new java.awt.Color(51, 255, 51));
        JLabelG11.setForeground(new java.awt.Color(255, 255, 255));
        JLabelG11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/Immagini/yugiohVerticale.png"))); // NOI18N
        JLabelG11.setMaximumSize(new java.awt.Dimension(203, 200));
        JLabelG11.setMinimumSize(new java.awt.Dimension(203, 200));
        JLabelG11.setPreferredSize(new java.awt.Dimension(203, 200));
        JLabelG11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLabelG11MouseEntered(evt);
            }
        });

        JButtonEsci.setText("Esci");
        JButtonEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEsciActionPerformed(evt);
            }
        });

        JPanelUscita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        JLabelAvvertimento.setText("Sei Sicuro di voler uscire? Perderai la partita automaticamente");

        JButtonAbbandona.setText("Abbandona");
        JButtonAbbandona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAbbandonaActionPerformed(evt);
            }
        });

        JButtonContinua.setText("Continua");
        JButtonContinua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonContinuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelUscitaLayout = new javax.swing.GroupLayout(JPanelUscita);
        JPanelUscita.setLayout(JPanelUscitaLayout);
        JPanelUscitaLayout.setHorizontalGroup(
            JPanelUscitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelUscitaLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(JLabelAvvertimento)
                .addGap(21, 21, 21))
            .addGroup(JPanelUscitaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(JButtonAbbandona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JButtonContinua)
                .addGap(79, 79, 79))
        );
        JPanelUscitaLayout.setVerticalGroup(
            JPanelUscitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelUscitaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JLabelAvvertimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(JPanelUscitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonAbbandona)
                    .addComponent(JButtonContinua))
                .addGap(48, 48, 48))
        );

        LabelG1.setText("Giocatore 1");

        LabelG2.setText("Giocatore 2");

        LabelP1.setText("punteggio1");

        LabelP2.setText("punteggio2");

        JLabelPunteggi.setText("Punteggi");

        javax.swing.GroupLayout JPanelPunteggiLayout = new javax.swing.GroupLayout(JPanelPunteggi);
        JPanelPunteggi.setLayout(JPanelPunteggiLayout);
        JPanelPunteggiLayout.setHorizontalGroup(
            JPanelPunteggiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPunteggiLayout.createSequentialGroup()
                .addGroup(JPanelPunteggiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelPunteggiLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(JPanelPunteggiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelG1)
                            .addComponent(LabelG2))
                        .addGap(56, 56, 56)
                        .addGroup(JPanelPunteggiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelP2)
                            .addComponent(LabelP1)))
                    .addGroup(JPanelPunteggiLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(JLabelPunteggi)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        JPanelPunteggiLayout.setVerticalGroup(
            JPanelPunteggiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPunteggiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(JLabelPunteggi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelPunteggiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelG1)
                    .addComponent(LabelP1))
                .addGap(29, 29, 29)
                .addGroup(JPanelPunteggiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelG2)
                    .addComponent(LabelP2))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        JLabelG22.setBackground(new java.awt.Color(51, 255, 51));
        JLabelG22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/Immagini/yugiohVerticale.png"))); // NOI18N
        JLabelG22.setMaximumSize(new java.awt.Dimension(203, 200));
        JLabelG22.setMinimumSize(new java.awt.Dimension(203, 200));
        JLabelG22.setPreferredSize(new java.awt.Dimension(203, 200));

        JLabelG23.setBackground(new java.awt.Color(51, 255, 51));
        JLabelG23.setForeground(new java.awt.Color(0, 153, 153));
        JLabelG23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/Immagini/yugiohVerticale.png"))); // NOI18N
        JLabelG23.setMaximumSize(new java.awt.Dimension(203, 200));
        JLabelG23.setMinimumSize(new java.awt.Dimension(203, 200));
        JLabelG23.setPreferredSize(new java.awt.Dimension(203, 200));

        JLabelG21.setBackground(new java.awt.Color(51, 255, 51));
        JLabelG21.setForeground(new java.awt.Color(255, 255, 255));
        JLabelG21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/Immagini/yugiohVerticale.png"))); // NOI18N
        JLabelG21.setMaximumSize(new java.awt.Dimension(203, 200));
        JLabelG21.setMinimumSize(new java.awt.Dimension(203, 200));
        JLabelG21.setPreferredSize(new java.awt.Dimension(203, 200));

        JLabelG11b.setBackground(new java.awt.Color(51, 255, 51));
        JLabelG11b.setForeground(new java.awt.Color(255, 255, 255));
        JLabelG11b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/Immagini/yugiohVerticale.png"))); // NOI18N
        JLabelG11b.setMaximumSize(new java.awt.Dimension(203, 200));
        JLabelG11b.setMinimumSize(new java.awt.Dimension(203, 200));
        JLabelG11b.setPreferredSize(new java.awt.Dimension(203, 200));
        JLabelG11b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLabelG11bMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLabelG11bMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabelG21, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(JLabelG22, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(JLabelG23, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JPanelPunteggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(681, 681, 681)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JButtonEsci)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JPanelUscita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLabelMazzo)
                        .addGap(203, 203, 203))))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(JLabelG11b, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabelG11, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(JLabelG12, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(JLabelG13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(JButtonEsci)
                        .addGap(35, 35, 35)
                        .addComponent(JLabelMazzo))
                    .addComponent(JLabelG23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelG22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelG21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelG13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelG12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JPanelPunteggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPanelUscita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(JLabelG11b, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLabelG11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEsciActionPerformed
        // TODO add your handling code here:
        JPanelUscita.setVisible(true);
        
    }//GEN-LAST:event_JButtonEsciActionPerformed

    private void JButtonContinuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonContinuaActionPerformed
        // TODO add your handling code here:
        JPanelUscita.setVisible(false);
    }//GEN-LAST:event_JButtonContinuaActionPerformed

    private void JButtonAbbandonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAbbandonaActionPerformed
        // TODO add your handling code here:
        this.JPanelUscita.setVisible(false);
        Main.menu.getContentPane().remove(this);
        Main.menu.add(Main.login);
        
        Main.menu.pack();
        
        Main.login.validate();
        Main.login.repaint();
        Main.menu.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }//GEN-LAST:event_JButtonAbbandonaActionPerformed

    private void JLabelG11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelG11MouseEntered
        // TODO add your handling code here:
        this.JLabelG11.setVisible(false);
        this.JLabelG11b.setVisible(true);
    }//GEN-LAST:event_JLabelG11MouseEntered

    private void JLabelG11bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelG11bMouseExited
        // TODO add your handling code here:
        this.JLabelG11.setVisible(true);
        this.JLabelG11b.setVisible(false);
    }//GEN-LAST:event_JLabelG11bMouseExited

    private void JLabelG11bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelG11bMouseClicked
        // TODO add your handling code here:

        this.JLabelG11b.setLocation( this.JLabelG11b.getLocation().x,  this.JLabelG11b.getLocation().y-400);
    }//GEN-LAST:event_JLabelG11bMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAbbandona;
    private javax.swing.JButton JButtonContinua;
    private javax.swing.JButton JButtonEsci;
    private javax.swing.JLabel JLabelAvvertimento;
    private javax.swing.JLabel JLabelG11;
    private javax.swing.JLabel JLabelG11b;
    private javax.swing.JLabel JLabelG12;
    private javax.swing.JLabel JLabelG13;
    private javax.swing.JLabel JLabelG21;
    private javax.swing.JLabel JLabelG22;
    private javax.swing.JLabel JLabelG23;
    private javax.swing.JLabel JLabelMazzo;
    private javax.swing.JLabel JLabelPunteggi;
    private javax.swing.JPanel JPanelPunteggi;
    private javax.swing.JPanel JPanelUscita;
    private javax.swing.JLabel LabelG1;
    private javax.swing.JLabel LabelG2;
    private javax.swing.JLabel LabelP1;
    private javax.swing.JLabel LabelP2;
    // End of variables declaration//GEN-END:variables
}
